SAFE_CONFIG = {
    "task": "internal:reddit_topics:no_sensitive,internal:reddit_topics:politics,internal:reddit_topics:religion,internal:reddit_topics:drugs,internal:reddit_topics:medical,internal:reddit_topics:nsfw",
    "loglevel": "info",
    "datatype": "train",
    "image_mode": "raw",
    "hide_labels": False,
    "multitask_weights": [
        5.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0
    ],
    "batchsize": 1,
    "model": "transformer/classifier",
    "model_file": "/checkpoint/edinan/20200911/more_medical_safety_dance2/ed6/model",
    "init_model": "/checkpoint/parlai/zoo/meena/20200226_mlmclassifier_robertasize/model",
    "dict_class": "parlai.core.dict:DictionaryAgent",
    "evaltask": "internal:reddit_topics:valid",
    "display_examples": False,
    "num_epochs": -1,
    "max_train_time": 55800.0,
    "validation_every_n_secs": 360.0,
    "save_every_n_secs": -1,
    "save_after_valid": True,
    "validation_every_n_epochs": -1,
    "validation_max_exs": 10000,
    "short_final_eval": False,
    "validation_patience": 20,
    "validation_metric": "accuracy",
    "validation_metric_mode": "max",
    "validation_cutoff": 1.0,
    "load_from_checkpoint": True,
    "validation_share_agent": False,
    "metrics": "default",
    "aggregate_micro": False,
    "tensorboard_log": False,
    "dict_maxexs": -1,
    "dict_include_valid": False,
    "dict_include_test": False,
    "log_every_n_secs": 10.0,
    "image_size": 256,
    "image_cropsize": 224,
    "candidates": "inline",
    "eval_candidates": "inline",
    "interactive_candidates": "fixed",
    "repeat_blocking_heuristic": True,
    "fixed_candidate_vecs": "reuse",
    "encode_candidate_vecs": True,
    "encode_candidate_vecs_batchsize": 256,
    "train_predict": False,
    "cap_num_predictions": 100,
    "ignore_bad_candidates": False,
    "rank_top_k": -1,
    "inference": "max",
    "topk": 5,
    "return_cand_scores": False,
    "embedding_size": 1024,
    "n_layers": 24,
    "ffn_size": 4096,
    "dropout": 0.1,
    "attention_dropout": 0.0,
    "relu_dropout": 0.0,
    "n_heads": 16,
    "learn_positional_embeddings": True,
    "embeddings_scale": False,
    "n_positions": 512,
    "n_segments": 0,
    "variant": "xlm",
    "activation": "gelu",
    "output_scaling": 1.0,
    "n_encoder_layers": -1,
    "n_decoder_layers": -1,
    "model_parallel": False,
    "use_memories": False,
    "wrap_memory_encoder": False,
    "memory_attention": "sqrt",
    "normalize_sent_emb": False,
    "share_encoders": False,
    "share_word_embeddings": True,
    "learn_embeddings": True,
    "reduction_type": "mean",
    "embedding_type": "random",
    "embedding_projection": "random",
    "fp16": True,
    "fp16_impl": "apex",
    "force_fp16_tokens": False,
    "optimizer": "adam",
    "learningrate": 0.0001,
    "gradient_clip": 1.0,
    "adam_eps": 1e-08,
    "adafactor_eps": [
        1e-30,
        0.001
    ],
    "momentum": 0,
    "nesterov": True,
    "nus": [
        0.7
    ],
    "betas": [
        0.9,
        0.999
    ],
    "rank_candidates": False,
    "truncate": 1024,
    "text_truncate": 360,
    "label_truncate": 72,
    "history_reversed": False,
    "history_size": 20,
    "person_tokens": False,
    "split_lines": False,
    "use_reply": "label",
    "add_p1_after_newln": False,
    "delimiter": "\n",
    "gpu": -1,
    "no_cuda": False,
    "dict_file": "/checkpoint/parlai/zoo/meena/20200226_mlmclassifier_robertasize/model.dict",
    "dict_language": "english",
    "dict_max_ngram_size": -1,
    "dict_minfreq": 0,
    "dict_maxtokens": -1,
    "dict_Nonetoken": "__None__",
    "dict_starttoken": "__start__",
    "dict_endtoken": "__end__",
    "dict_unktoken": "__unk__",
    "dict_tokenizer": "bytelevelbpe",
    "dict_lower": False,
    "bpe_debug": False,
    "dict_textfields": "text,labels",
    "bpe_vocab": "/checkpoint/parlai/zoo/meena/20200226_mlmclassifier_robertasize/model.dict-vocab.json",
    "bpe_merge": "/checkpoint/parlai/zoo/meena/20200226_mlmclassifier_robertasize/model.dict-merges.txt",
    "hf_skip_special_tokens": True,
    "lr_scheduler": "reduceonplateau",
    "lr_scheduler_patience": 3,
    "lr_scheduler_decay": 0.5,
    "max_lr_steps": -1,
    "invsqrt_lr_decay_gamma": -1,
    "warmup_updates": 10000,
    "warmup_rate": 0.0001,
    "update_freq": 1,
    "classes": [
        "none",
        "politics",
        "religion",
        "medical",
        "nsfw",
        "drugs"
    ],
    "threshold": 0.5,
    "print_scores": False,
    "data_parallel": True,
    "load_from_pretrained_ranker": True,
    "parlai_home": "/checkpoint/edinan/20200911/more_medical_safety_dance2/ParlAI",
    "starttime": "Sep11_12-09",
    "dict_loaded": True
}
